name: Run V2Ray Collector

on:
  schedule:
    # This runs approximately every 44 minutes.
    # Note: GitHub Actions schedules can have a slight delay.
    - cron: '*/44 * * * *'
  workflow_dispatch:

jobs:
  build:
    # The rest of the file is correct and does not need to be changed.
    # ...
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 55

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python script
        env:
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          TELETHON_SESSION: ${{ secrets.TELETHON_SESSION }}
        run: python main.py

      - name: Commit and Force Push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add -A
          if ! git diff --staged --quiet; then
            git commit -m "✅ Automated Config Update"
            git push --force
          else
            echo "No changes to commit."
          fi
