name: Run V2Ray Collector (Linux)

on:
  schedule:
    - cron: '*/44 * * * *'
  workflow_dispatch:

jobs:
  build:
    # This specifies the Linux runner
    runs-on: windows-latest
    
    permissions:
      contents: write
    timeout-minutes: 999

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        env:
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          TELETHON_SESSION: ${{ secrets.TELETHON_SESSION }}
        run: python main.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "✅ Automated Config Update (Linux)"
